services:
  postgres:
    image: docker.io/library/postgres:18.6
    container_name: tiny-lang-pg-dev
    ports:
      - "5432:5432"
    volumes:
      - tiny-lang-pg-dev:/var/lib/postgresql
    environment:
      POSTGRES_PASSWORD: GSkxOFn4MgUD+mjePeyEZQ==
      POSTGRES_DB: tiny_lang

  redis:
    image: docker.io/library/redis:8.10.0
    container_name: tiny-lang-redis-dev
    ports:
      - "6379:6379"
  
  rabbitmq:
    image: docker.io/library/rabbitmq:4.3.4-management-alpine
    container_name: tiny-lang-mq-dev
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: kAxmGthwfPHLx9JoVhULBg==
      RABBITMQ_DEFAULT_VHOST: /tiny-lang

  minio:
    image: docker.io/minio/minio:RELEASE.2025-04-22T22-12-26Z
    container_name: tiny-lang-minio-dev
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - tiny-lang-minio-dev:/data
      - ./certs:/root/.minio/certs:ro
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: ODfAsZQrcpVzhsAs4GGCUg==
    command: server /data --console-address ":9001"

  mailpit:
    image: docker.io/axllent/mailpit:v1.30.7
    container_name: tiny-lang-mailpit-dev
    ports:
      - "1025:1025"
      - "8025:8025"
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATABASE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    volumes:
      - tiny-lang-mailpit-dev:/data

volumes:
  tiny-lang-pg-dev:
  tiny-lang-minio-dev:
  tiny-lang-mailpit-dev:
