// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TinyLang.Database;

#nullable disable

namespace TinyLang.Database.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260729062434_AddBasicWordStudyModule")]
    partial class AddBasicWordStudyModule
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TinyLang.Entities.Article", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid");

                    b.Property<string>("ContentHtml")
                        .IsRequired()
                        .HasMaxLength(1000000)
                        .HasColumnType("character varying(1000000)");

                    b.Property<Guid?>("CoverMediaResourceId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LastEditorId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("PublishedById")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Summary")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CoverMediaResourceId");

                    b.HasIndex("PublishedById");

                    b.HasIndex("AuthorId", "CreatedAt");

                    b.HasIndex("LastEditorId", "UpdatedAt");

                    b.HasIndex("Status", "PublishedAt");

                    b.ToTable("articles", (string)null);
                });

            modelBuilder.Entity("TinyLang.Entities.ArticleCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("article_categories", (string)null);
                });

            modelBuilder.Entity("TinyLang.Entities.ArticleCategoryAssignment", b =>
                {
                    b.Property<Guid>("ArticleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ArticleCategoryId")
                        .HasColumnType("uuid");

                    b.HasKey("ArticleId", "ArticleCategoryId");

                    b.HasIndex("ArticleCategoryId", "ArticleId");

                    b.ToTable("article_category_assignments", (string)null);
                });

            modelBuilder.Entity("TinyLang.Entities.ArticleMediaResource", b =>
                {
                    b.Property<Guid>("ArticleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MediaResourceId")
                        .HasColumnType("uuid");

                    b.HasKey("ArticleId", "MediaResourceId");

                    b.HasIndex("MediaResourceId");

                    b.ToTable("article_media_resources", (string)null);
                });

            modelBuilder.Entity("TinyLang.Entities.AudioClip", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("Channels")
                        .HasColumnType("integer");

                    b.Property<Guid>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.Property<string>("ContainerFormat")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CurrentOutputVersion")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<double?>("DurationSeconds")
                        .HasColumnType("double precision");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("LanguageTag")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("character varying(35)");

                    b.Property<string>("LastFailureCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("OutputObjectName")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProcessingStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("PublicationStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("SampleRate")
                        .HasColumnType("integer");

                    b.Property<string>("SourceCodec")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("SourceMediaResourceId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SourceMediaResourceId")
                        .IsUnique();

                    b.HasIndex("ProcessingStatus", "PublicationStatus", "Id");

                    b.HasIndex("OwnerId", "ProcessingStatus", "PublicationStatus", "UpdatedAt", "Id");

                    b.ToTable("audio_clips", (string)null);
                });

            modelBuilder.Entity("TinyLang.Entities.AudioProcessingJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("AudioClipId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FailureCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset?>("LastDispatchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LeaseExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LeaseOwner")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OutputVersion")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AudioClipId")
                        .IsUnique()
                        .HasFilter("\"Status\" IN ('Queued', 'Processing')");

                    b.HasIndex("AudioClipId", "OutputVersion")
                        .IsUnique();

                    b.HasIndex("Status", "NextAttemptAt", "LeaseExpiresAt", "LastDispatchedAt", "CreatedAt", "Id");

                    b.ToTable("audio_processing_jobs", (string)null);
                });

            modelBuilder.Entity("TinyLang.Entities.ExampleSentence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AudioClipId")
                        .HasColumnType("uuid");

                    b.Property<string>("LanguageTag")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("character varying(35)");

                    b.Property<string>("Sentence")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Translation")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("TranslationLanguageTag")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("character varying(35)");

                    b.Property<Guid>("WordSenseId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AudioClipId");

                    b.HasIndex("WordSenseId", "SortOrder")
                        .IsUnique();

                    b.ToTable("example_sentences", (string)null);
                });

            modelBuilder.Entity("TinyLang.Entities.MediaResource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("ObjectName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("OriginalName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<long>("Size")
                        .HasColumnType("bigint");

                    b.Property<string>("StagingObjectName")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("UploadExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UploaderId")
                        .HasColumnType("uuid");

                    b.Property<string>("Url")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.HasKey("Id");

                    b.HasIndex("ObjectName")
                        .IsUnique();

                    b.HasIndex("StagingObjectName")
                        .IsUnique();

                    b.HasIndex("UploaderId", "Status");

                    b.HasIndex("Status", "UploadExpiresAt", "Id");

                    b.ToTable("media_resources", (string)null);
                });

            modelBuilder.Entity("TinyLang.Entities.MultipartUploadSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastFailureCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset?>("LeaseExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LeaseOwner")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MediaResourceId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PartCount")
                        .HasColumnType("integer");

                    b.Property<long>("PartSize")
                        .HasColumnType("bigint");

                    b.Property<string>("ProviderUploadId")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<bool>("StagingCleanupRequired")
                        .HasColumnType("boolean");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UploaderId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MediaResourceId")
                        .IsUnique();

                    b.HasIndex("UploaderId", "Status");

                    b.HasIndex("Status", "NextAttemptAt", "LeaseExpiresAt", "Id");

                    b.ToTable("multipart_upload_sessions", (string)null);
                });

            modelBuilder.Entity("TinyLang.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ClientIp")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeviceInfo")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("TokenVersion")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("UsageCount")
                        .HasColumnType("bigint");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId", "IsRevoked");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("TinyLang.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset?>("BannedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("BannedReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Bio")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsBanned")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Nickname")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("TokenVersion")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("TinyLang.Entities.UserVideoProgress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("LastPlayedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("PositionSeconds")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VideoId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VideoId");

                    b.HasIndex("UserId", "LastPlayedAt");

                    b.HasIndex("UserId", "VideoId")
                        .IsUnique();

                    b.ToTable("user_video_progress", (string)null);
                });

            modelBuilder.Entity("TinyLang.Entities.UserWordProgress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("FirstStudiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ForgottenCount")
                        .HasColumnType("integer");

                    b.Property<string>("LastResult")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset>("LastStudiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RememberedCount")
                        .HasColumnType("integer");

                    b.Property<int>("ReviewCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WordId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WordId");

                    b.HasIndex("UserId", "WordId")
                        .IsUnique();

                    b.HasIndex("UserId", "LastStudiedAt", "WordId");

                    b.ToTable("user_word_progress", null, t =>
                        {
                            t.HasCheckConstraint("CK_user_word_progress_counts", "\"ReviewCount\" >= 0 AND \"RememberedCount\" >= 0 AND \"ForgottenCount\" >= 0 AND \"ReviewCount\" = \"RememberedCount\" + \"ForgottenCount\"");
                        });
                });

            modelBuilder.Entity("TinyLang.Entities.Video", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AudioCodec")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.Property<string>("ContainerFormat")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CurrentOutputVersion")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int?>("DisplayHeight")
                        .HasColumnType("integer");

                    b.Property<int?>("DisplayWidth")
                        .HasColumnType("integer");

                    b.Property<double?>("DurationSeconds")
                        .HasColumnType("double precision");

                    b.Property<string>("LastFailureCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("MasterPlaylistObjectName")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("OriginalLanguage")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("character varying(35)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<string>("PosterObjectName")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("ProcessingStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("PublicationStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SourceMediaResourceId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VideoCodec")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("SourceMediaResourceId")
                        .IsUnique();

                    b.HasIndex("ProcessingStatus", "PublicationStatus", "PublishedAt", "Id");

                    b.HasIndex("OwnerId", "ProcessingStatus", "PublicationStatus", "UpdatedAt", "Id");

                    b.ToTable("videos", (string)null);
                });

            modelBuilder.Entity("TinyLang.Entities.VideoCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("video_categories", (string)null);
                });

            modelBuilder.Entity("TinyLang.Entities.VideoCategoryAssignment", b =>
                {
                    b.Property<Guid>("VideoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VideoCategoryId")
                        .HasColumnType("uuid");

                    b.HasKey("VideoId", "VideoCategoryId");

                    b.HasIndex("VideoCategoryId", "VideoId");

                    b.ToTable("video_category_assignments", (string)null);
                });

            modelBuilder.Entity("TinyLang.Entities.VideoProcessingJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FailureCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset?>("LastDispatchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LeaseExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LeaseOwner")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OutputVersion")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("VideoId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VideoId")
                        .IsUnique()
                        .HasFilter("\"Status\" IN ('Queued', 'Processing')");

                    b.HasIndex("VideoId", "OutputVersion")
                        .IsUnique();

                    b.HasIndex("Status", "NextAttemptAt", "LeaseExpiresAt", "LastDispatchedAt", "CreatedAt", "Id");

                    b.ToTable("video_processing_jobs", (string)null);
                });

            modelBuilder.Entity("TinyLang.Entities.VideoRendition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AudioBitrateKbps")
                        .HasColumnType("integer");

                    b.Property<string>("Codecs")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Height")
                        .HasColumnType("integer");

                    b.Property<Guid>("OutputVersion")
                        .HasColumnType("uuid");

                    b.Property<string>("PlaylistObjectName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<int>("TargetHeight")
                        .HasColumnType("integer");

                    b.Property<int>("VideoBitrateKbps")
                        .HasColumnType("integer");

                    b.Property<Guid>("VideoId")
                        .HasColumnType("uuid");

                    b.Property<int>("Width")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("VideoId", "OutputVersion", "TargetHeight")
                        .IsUnique();

                    b.ToTable("video_renditions", (string)null);
                });

            modelBuilder.Entity("TinyLang.Entities.VideoSubtitle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<string>("LanguageTag")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("character varying(35)");

                    b.Property<Guid>("MediaResourceId")
                        .HasColumnType("uuid");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("VideoId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MediaResourceId")
                        .IsUnique();

                    b.HasIndex("VideoId")
                        .IsUnique()
                        .HasFilter("\"IsDefault\" = TRUE");

                    b.HasIndex("VideoId", "LanguageTag")
                        .IsUnique();

                    b.ToTable("video_subtitles", (string)null);
                });

            modelBuilder.Entity("TinyLang.Entities.Word", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid");

                    b.Property<string>("Headword")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("LanguageTag")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("character varying(35)");

                    b.Property<Guid>("LastEditorId")
                        .HasColumnType("uuid");

                    b.Property<string>("NormalizedHeadword")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("LastEditorId");

                    b.HasIndex("LanguageTag", "NormalizedHeadword")
                        .IsUnique();

                    b.HasIndex("LanguageTag", "Status", "UpdatedAt", "Id");

                    b.HasIndex("Status", "LanguageTag", "PublishedAt", "Id");

                    b.ToTable("words", (string)null);
                });

            modelBuilder.Entity("TinyLang.Entities.WordPronunciation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccentTag")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("AudioClipId")
                        .HasColumnType("uuid");

                    b.Property<string>("Ipa")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<Guid>("WordId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AudioClipId");

                    b.HasIndex("WordId")
                        .IsUnique()
                        .HasFilter("\"IsDefault\" = TRUE");

                    b.HasIndex("WordId", "AudioClipId")
                        .IsUnique();

                    b.HasIndex("WordId", "SortOrder")
                        .IsUnique();

                    b.ToTable("word_pronunciations", (string)null);
                });

            modelBuilder.Entity("TinyLang.Entities.WordSense", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Definition")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("DefinitionLanguageTag")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("character varying(35)");

                    b.Property<string>("PartOfSpeech")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("UsageNote")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("WordId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WordId", "SortOrder")
                        .IsUnique();

                    b.ToTable("word_senses", (string)null);
                });

            modelBuilder.Entity("TinyLang.Entities.WordStudySession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("AbandonedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ActualCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IncludePreviouslyStudied")
                        .HasColumnType("boolean");

                    b.Property<string>("LanguageTag")
                        .HasMaxLength(35)
                        .HasColumnType("character varying(35)");

                    b.Property<int>("RequestedCount")
                        .HasColumnType("integer");

                    b.Property<string>("SelectionMode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("\"Status\" = 'Active'");

                    b.HasIndex("UserId", "StartedAt", "Id");

                    b.ToTable("word_study_sessions", null, t =>
                        {
                            t.HasCheckConstraint("CK_word_study_sessions_counts", "\"RequestedCount\" BETWEEN 1 AND 100 AND \"ActualCount\" BETWEEN 1 AND \"RequestedCount\"");
                        });
                });

            modelBuilder.Entity("TinyLang.Entities.WordStudySessionItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("AnsweredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("SkipReason")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("WordId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WordId");

                    b.HasIndex("SessionId", "Position")
                        .IsUnique();

                    b.HasIndex("SessionId", "WordId")
                        .IsUnique();

                    b.HasIndex("SessionId", "Status", "Position");

                    b.ToTable("word_study_session_items", null, t =>
                        {
                            t.HasCheckConstraint("CK_word_study_session_items_position", "\"Position\" >= 0");
                        });
                });

            modelBuilder.Entity("TinyLang.Entities.Article", b =>
                {
                    b.HasOne("TinyLang.Entities.User", "Author")
                        .WithMany("AuthoredArticles")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TinyLang.Entities.MediaResource", "CoverMediaResource")
                        .WithMany("CoveredArticles")
                        .HasForeignKey("CoverMediaResourceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TinyLang.Entities.User", "LastEditor")
                        .WithMany("EditedArticles")
                        .HasForeignKey("LastEditorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TinyLang.Entities.User", "PublishedBy")
                        .WithMany("PublishedArticles")
                        .HasForeignKey("PublishedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Author");

                    b.Navigation("CoverMediaResource");

                    b.Navigation("LastEditor");

                    b.Navigation("PublishedBy");
                });

            modelBuilder.Entity("TinyLang.Entities.ArticleCategoryAssignment", b =>
                {
                    b.HasOne("TinyLang.Entities.ArticleCategory", "ArticleCategory")
                        .WithMany("ArticleAssignments")
                        .HasForeignKey("ArticleCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TinyLang.Entities.Article", "Article")
                        .WithMany("CategoryAssignments")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Article");

                    b.Navigation("ArticleCategory");
                });

            modelBuilder.Entity("TinyLang.Entities.ArticleMediaResource", b =>
                {
                    b.HasOne("TinyLang.Entities.Article", "Article")
                        .WithMany("MediaResources")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TinyLang.Entities.MediaResource", "MediaResource")
                        .WithMany("ArticleMediaResources")
                        .HasForeignKey("MediaResourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Article");

                    b.Navigation("MediaResource");
                });

            modelBuilder.Entity("TinyLang.Entities.AudioClip", b =>
                {
                    b.HasOne("TinyLang.Entities.User", "Owner")
                        .WithMany("OwnedAudioClips")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TinyLang.Entities.MediaResource", "SourceMediaResource")
                        .WithOne("SourceAudioClip")
                        .HasForeignKey("TinyLang.Entities.AudioClip", "SourceMediaResourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Owner");

                    b.Navigation("SourceMediaResource");
                });

            modelBuilder.Entity("TinyLang.Entities.AudioProcessingJob", b =>
                {
                    b.HasOne("TinyLang.Entities.AudioClip", "AudioClip")
                        .WithMany("ProcessingJobs")
                        .HasForeignKey("AudioClipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AudioClip");
                });

            modelBuilder.Entity("TinyLang.Entities.ExampleSentence", b =>
                {
                    b.HasOne("TinyLang.Entities.AudioClip", "AudioClip")
                        .WithMany("ExampleSentences")
                        .HasForeignKey("AudioClipId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TinyLang.Entities.WordSense", "WordSense")
                        .WithMany("Examples")
                        .HasForeignKey("WordSenseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AudioClip");

                    b.Navigation("WordSense");
                });

            modelBuilder.Entity("TinyLang.Entities.MediaResource", b =>
                {
                    b.HasOne("TinyLang.Entities.User", "Uploader")
                        .WithMany("MediaResources")
                        .HasForeignKey("UploaderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Uploader");
                });

            modelBuilder.Entity("TinyLang.Entities.MultipartUploadSession", b =>
                {
                    b.HasOne("TinyLang.Entities.MediaResource", "MediaResource")
                        .WithOne("MultipartUploadSession")
                        .HasForeignKey("TinyLang.Entities.MultipartUploadSession", "MediaResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TinyLang.Entities.User", "Uploader")
                        .WithMany()
                        .HasForeignKey("UploaderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MediaResource");

                    b.Navigation("Uploader");
                });

            modelBuilder.Entity("TinyLang.Entities.RefreshToken", b =>
                {
                    b.HasOne("TinyLang.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TinyLang.Entities.UserVideoProgress", b =>
                {
                    b.HasOne("TinyLang.Entities.User", "User")
                        .WithMany("VideoProgress")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TinyLang.Entities.Video", "Video")
                        .WithMany("UserProgress")
                        .HasForeignKey("VideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Video");
                });

            modelBuilder.Entity("TinyLang.Entities.UserWordProgress", b =>
                {
                    b.HasOne("TinyLang.Entities.User", "User")
                        .WithMany("WordProgress")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TinyLang.Entities.Word", "Word")
                        .WithMany("UserProgress")
                        .HasForeignKey("WordId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Word");
                });

            modelBuilder.Entity("TinyLang.Entities.Video", b =>
                {
                    b.HasOne("TinyLang.Entities.User", "Owner")
                        .WithMany("OwnedVideos")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TinyLang.Entities.MediaResource", "SourceMediaResource")
                        .WithOne("SourceVideo")
                        .HasForeignKey("TinyLang.Entities.Video", "SourceMediaResourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Owner");

                    b.Navigation("SourceMediaResource");
                });

            modelBuilder.Entity("TinyLang.Entities.VideoCategoryAssignment", b =>
                {
                    b.HasOne("TinyLang.Entities.VideoCategory", "VideoCategory")
                        .WithMany("VideoAssignments")
                        .HasForeignKey("VideoCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TinyLang.Entities.Video", "Video")
                        .WithMany("CategoryAssignments")
                        .HasForeignKey("VideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Video");

                    b.Navigation("VideoCategory");
                });

            modelBuilder.Entity("TinyLang.Entities.VideoProcessingJob", b =>
                {
                    b.HasOne("TinyLang.Entities.Video", "Video")
                        .WithMany("ProcessingJobs")
                        .HasForeignKey("VideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Video");
                });

            modelBuilder.Entity("TinyLang.Entities.VideoRendition", b =>
                {
                    b.HasOne("TinyLang.Entities.Video", "Video")
                        .WithMany("Renditions")
                        .HasForeignKey("VideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Video");
                });

            modelBuilder.Entity("TinyLang.Entities.VideoSubtitle", b =>
                {
                    b.HasOne("TinyLang.Entities.MediaResource", "MediaResource")
                        .WithOne("VideoSubtitle")
                        .HasForeignKey("TinyLang.Entities.VideoSubtitle", "MediaResourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TinyLang.Entities.Video", "Video")
                        .WithMany("Subtitles")
                        .HasForeignKey("VideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MediaResource");

                    b.Navigation("Video");
                });

            modelBuilder.Entity("TinyLang.Entities.Word", b =>
                {
                    b.HasOne("TinyLang.Entities.User", "CreatedBy")
                        .WithMany("CreatedWords")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TinyLang.Entities.User", "LastEditor")
                        .WithMany("EditedWords")
                        .HasForeignKey("LastEditorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("LastEditor");
                });

            modelBuilder.Entity("TinyLang.Entities.WordPronunciation", b =>
                {
                    b.HasOne("TinyLang.Entities.AudioClip", "AudioClip")
                        .WithMany("WordPronunciations")
                        .HasForeignKey("AudioClipId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TinyLang.Entities.Word", "Word")
                        .WithMany("Pronunciations")
                        .HasForeignKey("WordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AudioClip");

                    b.Navigation("Word");
                });

            modelBuilder.Entity("TinyLang.Entities.WordSense", b =>
                {
                    b.HasOne("TinyLang.Entities.Word", "Word")
                        .WithMany("Senses")
                        .HasForeignKey("WordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Word");
                });

            modelBuilder.Entity("TinyLang.Entities.WordStudySession", b =>
                {
                    b.HasOne("TinyLang.Entities.User", "User")
                        .WithMany("WordStudySessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TinyLang.Entities.WordStudySessionItem", b =>
                {
                    b.HasOne("TinyLang.Entities.WordStudySession", "Session")
                        .WithMany("Items")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TinyLang.Entities.Word", "Word")
                        .WithMany("StudySessionItems")
                        .HasForeignKey("WordId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Session");

                    b.Navigation("Word");
                });

            modelBuilder.Entity("TinyLang.Entities.Article", b =>
                {
                    b.Navigation("CategoryAssignments");

                    b.Navigation("MediaResources");
                });

            modelBuilder.Entity("TinyLang.Entities.ArticleCategory", b =>
                {
                    b.Navigation("ArticleAssignments");
                });

            modelBuilder.Entity("TinyLang.Entities.AudioClip", b =>
                {
                    b.Navigation("ExampleSentences");

                    b.Navigation("ProcessingJobs");

                    b.Navigation("WordPronunciations");
                });

            modelBuilder.Entity("TinyLang.Entities.MediaResource", b =>
                {
                    b.Navigation("ArticleMediaResources");

                    b.Navigation("CoveredArticles");

                    b.Navigation("MultipartUploadSession");

                    b.Navigation("SourceAudioClip");

                    b.Navigation("SourceVideo");

                    b.Navigation("VideoSubtitle");
                });

            modelBuilder.Entity("TinyLang.Entities.User", b =>
                {
                    b.Navigation("AuthoredArticles");

                    b.Navigation("CreatedWords");

                    b.Navigation("EditedArticles");

                    b.Navigation("EditedWords");

                    b.Navigation("MediaResources");

                    b.Navigation("OwnedAudioClips");

                    b.Navigation("OwnedVideos");

                    b.Navigation("PublishedArticles");

                    b.Navigation("RefreshTokens");

                    b.Navigation("VideoProgress");

                    b.Navigation("WordProgress");

                    b.Navigation("WordStudySessions");
                });

            modelBuilder.Entity("TinyLang.Entities.Video", b =>
                {
                    b.Navigation("CategoryAssignments");

                    b.Navigation("ProcessingJobs");

                    b.Navigation("Renditions");

                    b.Navigation("Subtitles");

                    b.Navigation("UserProgress");
                });

            modelBuilder.Entity("TinyLang.Entities.VideoCategory", b =>
                {
                    b.Navigation("VideoAssignments");
                });

            modelBuilder.Entity("TinyLang.Entities.Word", b =>
                {
                    b.Navigation("Pronunciations");

                    b.Navigation("Senses");

                    b.Navigation("StudySessionItems");

                    b.Navigation("UserProgress");
                });

            modelBuilder.Entity("TinyLang.Entities.WordSense", b =>
                {
                    b.Navigation("Examples");
                });

            modelBuilder.Entity("TinyLang.Entities.WordStudySession", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
